#!/bin/bash



echo "Building Catalogue"
/home/rjn/Apps/calibre2opds/run.sh

echo "renaming _search to search"
mv docs/_search docs/search

echo "fixing link"

echo "backing up Calibre Library"
echo "updating git ignore"
find .  -size +100M -prune .git | sed 's|^\./||g' | cat >> .gitignore
find .  -size +100M -prune .git -exec cp --no-clobber --parents -t ~/Dropbox/big_books "{}" +
echo "uploading books to github..."
git add .
git commit -m "backing up"
git push
echo "Calibre backup done"
