#!/bin/bash



echo "Building Catalogue"
rm -rf docs
/home/rjn/Apps/calibre2opds/run.sh

echo "renaming _search to search"
mv docs/_search docs/search

echo "fixing link"
sed -i 's/\_search/\.\/search/g' docs/index.html

echo "fixing footer"
sed -i '/<footer>/,/<\/footer>/{//!d}' docs/search/search.html

echo "fixing html Titles"
python3 process_html.py

echo "updating git ignore"
find .  -size +100M -prune '.git' | sed 's|^\./||g' | cat >> .gitignore

echo "moving big files to dropbox"
find .  -size +100M -prune '.git' -exec cp --no-clobber --parents -t ~/Dropbox/big_books "{}" +


echo "Staging Changes"
git add .

echo "making commit"
git commit -m "backing up"

echo "Pushing to github"
git push
echo "Calibre backup done"
